// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Yaaf.AdvancedBuilding")]
[assembly: AssemblyProductAttribute("Yaaf.AdvancedBuilding")]
[assembly: AssemblyCopyrightAttribute("Yaaf.AdvancedBuilding Copyright © Matthias Dittrich 2015")]
[assembly: AssemblyVersionAttribute("0.1.4")]
[assembly: AssemblyFileVersionAttribute("0.1.4")]
[assembly: AssemblyInformationalVersionAttribute("0.1.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.4";
    }
}
